### ISSUE TITLE
Ownpad doesn't open .pad file

### ISSUE THREAD

**Issue by sebastienserre** [otetard/ownpad#91]
Hello, 
On NC 16.0.4, I can't succed opening a Calc file...

```
sudo -u www-data php occ files:scan --all
```

sens lots of error in red msgs

```
Exception during scan: array_merge(): Argument #2 is not an array
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(2, 'array_merge(): ...', '/var/www/nextcl...', 149, Array)
#1 /var/www/nextcloud/lib/private/Files/Type/Detection.php(149): array_merge(Array, NULL)
#2 /var/www/nextcloud/lib/private/Files/Type/Detection.php(170): OC\Files\Type\Detection->loadMappings()
#3 /var/www/nextcloud/lib/private/Files/Storage/Common.php(246): OC\Files\Type\Detection->detectPath('files_encryptio...')
#4 /var/www/nextcloud/lib/private/Files/Storage/Common.php(675): OC\Files\Storage\Common->getMimeType('files_encryptio...')
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(582): OC\Files\Storage\Common->getMetaData('files_encryptio...')
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php(175): OC\Files\Storage\Wrapper\Wrapper->getMetaData('files_encryptio...')
#7 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(582): OC\Files\Storage\Wrapper\Encryption->getMetaData('files_encryptio...')
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(112): OC\Files\Storage\Wrapper\Wrapper->getMetaData('files_encryptio...')
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(150): OC\Files\Cache\Scanner->getData('files_encryptio...')
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(438): OC\Files\Cache\Scanner->scanFile('files_encryptio...', 3, 2722, Object(OC\Files\Cache\CacheEntry), true)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(406): OC\Files\Cache\Scanner->handleChildren('files_encryptio...', true, 3, 2722, true, 0)
#12 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2722, true)
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2721, true)
#14 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 1054403, true)
#15 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 1054402, true)
#16 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2635, true)
#17 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2634, true)
#18 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, 1861, true)
#19 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#20 /var/www/nextcloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/matt', true, NULL)
#21 /var/www/nextcloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('matt', '/matt', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#22 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/nextcloud/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/nextcloud/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#28 /var/www/nextcloud/console.php(97): OC\Console\Application->run()
#29 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#30 {main}
Starting scan for user 2 out of 3 (sebastienserre)
Exception during scan: array_merge(): Argument #2 is not an array
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(2, 'array_merge(): ...', '/var/www/nextcl...', 149, Array)
#1 /var/www/nextcloud/lib/private/Files/Type/Detection.php(149): array_merge(Array, NULL)
#2 /var/www/nextcloud/lib/private/Files/Type/Detection.php(170): OC\Files\Type\Detection->loadMappings()
#3 /var/www/nextcloud/lib/private/Files/Storage/Common.php(246): OC\Files\Type\Detection->detectPath('files_encryptio...')
#4 /var/www/nextcloud/lib/private/Files/Storage/Common.php(675): OC\Files\Storage\Common->getMimeType('files_encryptio...')
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php(175): OC\Files\Storage\Common->getMetaData('files_encryptio...')
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(582): OC\Files\Storage\Wrapper\Encryption->getMetaData('files_encryptio...')
#7 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(112): OC\Files\Storage\Wrapper\Wrapper->getMetaData('files_encryptio...')
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(150): OC\Files\Cache\Scanner->getData('files_encryptio...')
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(438): OC\Files\Cache\Scanner->scanFile('files_encryptio...', 3, 10758, Object(OC\Files\Cache\CacheEntry), true)
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(406): OC\Files\Cache\Scanner->handleChildren('files_encryptio...', true, 3, 10758, true, 0)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 10758, true)
#12 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 10757, true)
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 1054397, true)
#14 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 1054396, true)
#15 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2363, true)
#16 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_encryptio...', true, 3, 2362, true)
#17 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, 5, true)
#18 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#19 /var/www/nextcloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/sebastienserre', true, NULL)
#20 /var/www/nextcloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('sebastienserre', '/sebastienserre', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#21 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/nextcloud/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 /var/www/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#26 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#27 /var/www/nextcloud/console.php(97): OC\Console\Application->run()
#28 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#29 {main}
Starting scan for user 3 out of 3 (Tom)
Exception during scan: array_merge(): Argument #2 is not an array
#0 [internal function]: OCA\Files\Command\Scan->exceptionErrorHandler(2, 'array_merge(): ...', '/var/www/nextcl...', 149, Array)
#1 /var/www/nextcloud/lib/private/Files/Type/Detection.php(149): array_merge(Array, NULL)
#2 /var/www/nextcloud/lib/private/Files/Type/Detection.php(170): OC\Files\Type\Detection->loadMappings()
#3 /var/www/nextcloud/lib/private/Files/Storage/Common.php(246): OC\Files\Type\Detection->detectPath('files_external/...')
#4 /var/www/nextcloud/lib/private/Files/Storage/Common.php(675): OC\Files\Storage\Common->getMimeType('files_external/...')
#5 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(582): OC\Files\Storage\Common->getMetaData('files_external/...')
#6 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Encryption.php(175): OC\Files\Storage\Wrapper\Wrapper->getMetaData('files_external/...')
#7 /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php(582): OC\Files\Storage\Wrapper\Encryption->getMetaData('files_external/...')
#8 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(112): OC\Files\Storage\Wrapper\Wrapper->getMetaData('files_external/...')
#9 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(150): OC\Files\Cache\Scanner->getData('files_external/...')
#10 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(438): OC\Files\Cache\Scanner->scanFile('files_external/...', 3, 1054820, NULL, true)
#11 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(406): OC\Files\Cache\Scanner->handleChildren('files_external', true, 3, 1054820, true, 0)
#12 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(409): OC\Files\Cache\Scanner->scanChildren('files_external', true, 3, 1054820, true)
#13 /var/www/nextcloud/lib/private/Files/Cache/Scanner.php(338): OC\Files\Cache\Scanner->scanChildren('', true, 3, 469838, true)
#14 /var/www/nextcloud/lib/private/Files/Utils/Scanner.php(245): OC\Files\Cache\Scanner->scan('', true, 3)
#15 /var/www/nextcloud/apps/files/lib/Command/Scan.php(145): OC\Files\Utils\Scanner->scan('/Tom', true, NULL)
#16 /var/www/nextcloud/apps/files/lib/Command/Scan.php(201): OCA\Files\Command\Scan->scanFiles('Tom', '/Tom', Object(Symfony\Component\Console\Output\ConsoleOutput), false, true, false)
#17 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OCA\Files\Command\Scan->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/nextcloud/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/nextcloud/3rdparty/symfony/console/Application.php(901): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/nextcloud/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OCA\Files\Command\Scan), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/nextcloud/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/nextcloud/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/nextcloud/console.php(97): OC\Console\Application->run()
#24 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#25 {main}
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 16      | 0     | 00:00:01     |
+---------+-------+--------------+
```

**Comment by otetard** [comment]
I think that your `config/mimetypemapping.json` is not a valid file. Feel free to reopen this issue if it’s still relevant.
